service:
  type: NodePort
  nodePort: 31234
image:
  repository: 5599169467181.dkr.ecr.ap-northeast-2.amazonaws.com/test-image
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "86"
imagePullSecrets: ap-northeast-2-ecr-registry
resources:
  limits:
    cpu: 0.1
    memory: 128Mi
  requests:
    cpu: 0.1
    memory: 128Mi
replicaCount: 2
