# service:
#   type: NodePort
#   nodePort: 80
service:
  type: ClusterIP
  nodePort: 8012
  
image:
  repository: 559916946718.dkr.ecr.ap-northeast-2.amazonaws.com/test-image
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "25"
imagePullSecrets:
  - name: ap-northeast-2-ecr-registry
resources:
  limits:
    cpu: 0.1
    memory: 128Mi
  requests:
    cpu: 0.1
    memory: 128Mi
replicaCount: 2

volumeMounts:
  name: file-volume
  mountPath: /mount
  configMap:
    name: cm-file